#!/usr/bin/env bash

# auto-discovery kube configs

# if KUBECONFIG already set - exit
if [ -n "$KUBECONFIG" ]; then
  return 0
fi



# default kubeconfig
FILES="$HOME/.kube/default"

KUBE_DIR="$HOME/.kube/config"

if [ ! -d "$KUBE_DIR" ]; then
  echo "$KUBE_DIR does not exist."
fi

for cluster in `find $KUBE_DIR -type f -name "*.yaml"`
do
  FILES="$cluster:$FILES"
done

export KUBECONFIG=$FILES

